# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ nvidia_x11 ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/89b6e612-f1a8-4623-97f6-e61e2f708587";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBC5-0C87";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f82fed82-7068-4279-bdb6-9c638e04fee9"; }
    ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

  services.xserver.videoDrivers = [ "nvidia" ];
}
